on: push

name: ci
jobs:
  latest-version:
    env:
      INPUT_OWNER: kopach
      INPUT_REPO: karma-sabarivka-reporter
    name: Get Latest Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get Latest Release
      uses: abatilo/release-info-action@v1.0.0
      with:
        owner: abatilo
        repo: release-info-action
        
    - name: Info
      run: |
        echo "tag: ${{ steps.latest_version.outputs.latest_tag }}"
        echo "owner ${{ $INPUT_OWNER }}"
